[project]
name = "download-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sentence-transformers>=5.1.0",
    "tiktoken>=0.11.0",
]
