on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ap-northeast-1
      - run: aws s3 cp s3://cm-natsume-data-bucket/model.tar .
      - run: tar xf model.tar
      - run: find . -type f | sort